# Variável para Data Driven Pytest
examples_invalid_login_fields = [
    ("username", "123"),
    ("username", "123.to_i"),
    ("username", "None"),
    ("username", "Null"),
    ("username", "number_negative"),
    ("username", "boolean_true"),
    ("username", "boolean_false"),
    ("username", "256.characters_type_string"),
    ("username", "256.characters_type_numbers"),
    ("username", "Array"),
    ("username", "Hash"),
    ("password", "123"),
    ("password", "123.to_i"),
    ("password", "None"),
    ("password", "Null"),
    ("password", "number_negative"),
    ("password", "boolean_true"),
    ("password", "boolean_false"),
    ("password", "256.characters_type_string"),
    ("password", "256.characters_type_numbers"),
    ("password", "Array"),
    ("password", "Hash"),
]

# Variável para Data Driven Pytest
examples_sort_product = [
    ("A to Z"),
    ("Z to A"),
    ("Lo to Hi"),
    ("Hi to Lo"),
]

# Variável para Data Driven Pytest
examples_invalid_data_checkout = [
    ("firstName", "123"),
    ("firstName", "123.to_i"),
    ("firstName", "None"),
    ("firstName", "Null"),
    ("firstName", "number_negative"),
    ("firstName", "boolean_true"),
    ("firstName", "boolean_false"),
    ("firstName", "256.characters_type_string"),
    ("firstName", "256.characters_type_numbers"),
    ("firstName", "Array"),
    ("firstName", "Hash"),
    ("firstName", " "),
    ("lastName", "123"),
    ("lastName", "123.to_i"),
    ("lastName", "None"),
    ("lastName", "Null"),
    ("lastName", "number_negative"),
    ("lastName", "boolean_true"),
    ("lastName", "boolean_false"),
    ("lastName", "256.characters_type_string"),
    ("lastName", "256.characters_type_numbers"),
    ("lastName", "Array"),
    ("lastName", "Hash"),
    ("lastName", " "),
    ("postalCode", "123"),
    ("postalCode", "123.to_i"),
    ("postalCode", "None"),
    ("postalCode", "Null"),
    ("postalCode", "number_negative"),
    ("postalCode", "boolean_true"),
    ("postalCode", "boolean_false"),
    ("postalCode", "256.characters_type_string"),
    ("postalCode", "256.characters_type_numbers"),
    ("postalCode", "Array"),
    ("postalCode", "Hash"),
    ("postalCode", " "),
]